[project]
name = "lowcode-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Owen", email = "ycode.dev@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
lowcode-api = "lowcode_api:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
